# Generated by Django 3.1.5 on 2021-01-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPT', '0002_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.EmailField(default='khoa@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='phone',
            field=models.CharField(default='0905xxx', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='type',
            field=models.CharField(choices=[('ET', 'External Type'), ('IT', 'Internal Type')], default='ET', max_length=2),
        ),
        migrations.AddField(
            model_name='trainer',
            name='working_place',
            field=models.CharField(default='FPT', max_length=50),
            preserve_default=False,
        ),
    ]
