# Generated by Django 3.1.5 on 2021-01-18 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FPT', '0003_auto_20210118_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='FPT.user')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='khoa@gmail.com', max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('age', models.IntegerField(default=18)),
                ('dot', models.DateField(default='03/05/2000')),
                ('education', models.CharField(max_length=50)),
                ('experience', models.IntegerField(default=1)),
                ('location', models.CharField(max_length=50)),
                ('toeic_score', models.IntegerField(default=1)),
                ('department', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='HR', max_length=20),
        ),
    ]
