# Generated by Django 3.1.5 on 2021-01-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPT', '0009_auto_20210118_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(default='FPT', max_length=20),
        ),
    ]
