# Generated by Django 3.1.5 on 2021-01-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPT', '0012_auto_20210120_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='name',
        ),
        migrations.AddField(
            model_name='trainer',
            name='education',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='education',
            field=models.CharField(blank=True, default='FPT Education', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='location',
            field=models.CharField(blank=True, default='Da Nang', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='phone',
            field=models.CharField(blank=True, default='09xx', max_length=12),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='toeic_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='working_place',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
