# Generated by Django 3.1.5 on 2021-01-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPT', '0014_auto_20210121_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='age',
            field=models.IntegerField(blank=True, default=18),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='dot',
            field=models.DateField(blank=True, default='03/05/2000'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='experience',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='toeic_score',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
