# Generated by Django 3.1.5 on 2021-01-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPT', '0015_auto_20210123_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='dot',
            field=models.DateField(blank=True, default=''),
        ),
    ]
