# Generated by Django 3.1.5 on 2021-01-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPT', '0017_auto_20210125_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
