# Generated by Django 3.1.5 on 2021-01-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPT', '0018_auto_20210126_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
