# Generated by Django 3.1.5 on 2021-01-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPT', '0023_auto_20210126_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(to='FPT.Category'),
        ),
    ]
