# Generated by Django 3.1.5 on 2021-01-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPT', '0028_auto_20210128_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='education',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='type',
            field=models.CharField(choices=[('ET', 'External Type'), ('IT', 'Internal Type')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='working_place',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
