# Generated by Django 3.1.5 on 2021-01-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPT', '0029_auto_20210128_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='limit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
