# Generated by Django 3.1.5 on 2021-02-02 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FPT', '0031_request_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='limit_time',
        ),
    ]
