# Generated by Django 3.1.5 on 2021-02-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FPT', '0032_remove_request_limit_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_permission',
        ),
    ]
